#!/bin/sh
### BEGIN INIT INFO
# Provides:          hipache-poc-service
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Docker Container with redis-server & hipache
# Description:       Docker Container with redis-server & hipache
### END INIT INFO


USER="root"

CMD="docker run -d -p :6379 -p :80 samalba/hipache supervisord -n"

NAME=`baseNAME $0`
CONTAINER_FILE="/var/run/$NAME.cid"


# PID_FILE="/var/run/$NAME.pid"
# /sbin/start-stop-daemon --user $USER --start --pidfile $PID_FILE --make-pidfile --background --chuid $USER --exec $CMD
# /sbin/start-stop-daemon --user $USER --stop --pidfile $PID_FILE

getContainerId() {
	cat "$CONTAINER_FILE"
}

isRunning() {
	[ -f "$CONTAINER_FILE" ] && docker ps -a | grep `getContainerId` > /dev/null 2>&1
}


case $1 in
	start)
		if isRunning; then
			echo "Already started"
		else
			echo "Starting $NAME"


			sudo -u "$USER" $CMD > $CONTAINER_FILE
			if ! isRunning; then
				echo "Unable to start"
				exit 1
			fi
		fi
	;;
	stop)
		if isRunning; then
			echo "Stopping $NAME"
			docker stop `getContainerId` > /dev/null 2>&1
			rm -f "$CONTAINER_FILE"
		else
			echo "Not running"
		fi
	;;
	restart)
		$0 stop
		$0 start
	;;
esac

exit 0