#!/bin/sh
### BEGIN INIT INFO
# Provides:          
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO


user="root"

CMD="docker run -d -p :6379 -p :80 samalba/hipache supervisord -n"


name=`basename $0`

stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

container_file="/var/run/$name.cid"


getContainerId() {
	cat "$container_file"
}

isRunning() {
	[ -f "$container_file" ] && docker ps -a | grep `getContainerId` > /dev/null 2>&1
}



case $1 in
	start)
		if isRunning; then
			echo "Already started"
		else
			echo "Starting $name"
			sudo -u "$user" $CMD > $container_file
			if ! isRunning; then
				echo "Unable to start"
				exit 1
			fi
		fi
	;;
	stop)
		if isRunning; then
			echo "Stopping $name"
			docker stop `getContainerId`
			rm "$container_file"
		else
			echo "Not running"
		fi
	;;
	restart)
		$0 stop
		$0 start
	;;
esac

exit 0